import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import type { ScanResult, InterpretedFinding, Severity, CheckCategory } from '../scanner/types.js';
import { log } from '../utils/logger.js';
import { severityOrder, formatDuration } from '../utils/shared.js';

export function writeBountyReport(result: ScanResult, outputPath: string): void {
  const md = generateBountyMarkdown(result);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, md, 'utf-8');
  log.info(`Bug bounty report written to: ${outputPath}`);
}

function generateBountyMarkdown(result: ScanResult): string {
  const sorted = [...result.interpretedFindings].sort(
    (a, b) => severityOrder(b.severity) - severityOrder(a.severity),
  );

  const lines: string[] = [];

  // Header
  lines.push('# Security Assessment Report');
  lines.push('');
  lines.push(`**Target:** ${result.targetUrl}`);
  lines.push(`**Scan Date:** ${new Date(result.startedAt).toISOString().split('T')[0]}`);
  lines.push(`**Profile:** ${result.profile}`);
  lines.push(`**Pages Scanned:** ${result.pagesScanned}`);
  lines.push(`**Duration:** ${formatDuration(result.startedAt, result.completedAt)}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Critical | ${result.summary.bySeverity.critical} |`);
  lines.push(`| High | ${result.summary.bySeverity.high} |`);
  lines.push(`| Medium | ${result.summary.bySeverity.medium} |`);
  lines.push(`| Low | ${result.summary.bySeverity.low} |`);
  lines.push(`| Info | ${result.summary.bySeverity.info} |`);
  lines.push(`| **Total** | **${result.summary.totalInterpretedFindings}** |`);
  lines.push('');

  if (sorted.length === 0) {
    lines.push('No actionable vulnerabilities were identified during this assessment.');
    lines.push('');
    return lines.join('\n');
  }

  // Findings
  lines.push('---');
  lines.push('');

  for (let i = 0; i < sorted.length; i++) {
    lines.push(...renderBountyFinding(i + 1, sorted[i]));
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by SecBot — AI-Powered Security Scanner*');
  lines.push('');

  return lines.join('\n');
}

function renderBountyFinding(index: number, finding: InterpretedFinding): string[] {
  const lines: string[] = [];
  const cwe = mapToCwe(finding);

  lines.push(`## ${index}. [${finding.severity.toUpperCase()}] ${finding.title}`);
  lines.push('');
  lines.push(`**Asset:** ${finding.affectedUrls?.[0] ?? 'N/A'}`);
  lines.push(`**Weakness:** ${cwe}`);
  lines.push(`**OWASP Category:** ${finding.owaspCategory}`);
  lines.push(`**Confidence:** ${finding.confidence}`);
  lines.push('');

  // Description
  lines.push('### Description');
  lines.push('');
  lines.push(finding.description);
  lines.push('');

  // Steps to Reproduce
  if (finding.reproductionSteps?.length > 0) {
    lines.push('### Steps to Reproduce');
    lines.push('');
    for (const step of finding.reproductionSteps) {
      lines.push(step);
    }
    lines.push('');
  }

  // Impact
  lines.push('### Impact');
  lines.push('');
  lines.push(finding.impact);
  lines.push('');

  // Affected URLs as evidence
  if (finding.affectedUrls?.length > 0) {
    lines.push('### Supporting Evidence');
    lines.push('');
    lines.push('**Affected URLs:**');
    for (const url of finding.affectedUrls.slice(0, 10)) {
      lines.push(`- ${url}`);
    }
    if (finding.affectedUrls.length > 10) {
      lines.push(`- ... and ${finding.affectedUrls.length - 10} more`);
    }
    lines.push('');
  }

  // Code example as evidence
  if (finding.codeExample) {
    lines.push('**HTTP Request/Response:**');
    lines.push('');
    lines.push('```');
    lines.push(finding.codeExample);
    lines.push('```');
    lines.push('');
  }

  // Remediation
  lines.push('### Suggested Remediation');
  lines.push('');
  lines.push(finding.suggestedFix);
  lines.push('');
  lines.push('---');
  lines.push('');

  return lines;
}

function mapToCwe(finding: InterpretedFinding): string {
  // Infer category from title/owasp
  const title = finding.title.toLowerCase();
  const owasp = finding.owaspCategory.toLowerCase();

  if (title.includes('xss') || title.includes('cross-site scripting')) return 'CWE-79: Improper Neutralization of Input During Web Page Generation';
  if (title.includes('sql') || title.includes('sqli')) return 'CWE-89: SQL Injection';
  if (title.includes('cors')) return 'CWE-942: Permissive Cross-domain Policy with Untrusted Domains';
  if (title.includes('redirect')) return 'CWE-601: URL Redirection to Untrusted Site';
  if (title.includes('traversal') || title.includes('path')) return 'CWE-22: Path Traversal';
  if (title.includes('hsts') || title.includes('transport')) return 'CWE-319: Cleartext Transmission of Sensitive Information';
  if (title.includes('csp') || title.includes('content-security')) return 'CWE-693: Protection Mechanism Failure';
  if (title.includes('cookie')) return 'CWE-614: Sensitive Cookie in HTTPS Session Without Secure Attribute';
  if (title.includes('clickjack') || title.includes('frame')) return 'CWE-1021: Improper Restriction of Rendered UI Layers';
  if (title.includes('info') || title.includes('disclosure') || title.includes('leakage')) return 'CWE-200: Exposure of Sensitive Information';
  if (title.includes('mixed content')) return 'CWE-311: Missing Encryption of Sensitive Data';

  if (owasp.includes('injection')) return 'CWE-74: Injection';
  if (owasp.includes('cryptographic')) return 'CWE-310: Cryptographic Issues';
  if (owasp.includes('access control')) return 'CWE-284: Improper Access Control';
  if (owasp.includes('misconfiguration')) return 'CWE-16: Configuration';

  return 'CWE-Unknown';
}

// severityOrder and formatDuration imported from shared utils
